server.port=8084

spring.application.name=payment-notification-service

spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:movie_ticket_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.rabbitmq.exchange=movie.booking.events
app.rabbitmq.booking-created-queue=payment.booking-created.q
app.rabbitmq.payment-completed-queue=notification.payment-completed.q
app.rabbitmq.booking-failed-queue=booking.booking-failed.q
app.rabbitmq.user-registered-queue=notification.user-registered.q
app.rabbitmq.notification-dispatched-queue=notification.dispatched.q
app.rabbitmq.booking-created-routing-key=BOOKING_CREATED
app.rabbitmq.payment-completed-routing-key=PAYMENT_COMPLETED
app.rabbitmq.booking-failed-routing-key=BOOKING_FAILED
app.rabbitmq.user-registered-routing-key=USER_REGISTERED
app.rabbitmq.notification-dispatched-routing-key=NOTIFICATION_DISPATCHED

app.websocket.notification-topic=/topic/notifications
app.cors.allowed-origins[0]=http://192.168.1.8:3000

management.endpoints.web.exposure.include=health,info
